#!/usr/bin/env python3
"""Build deterministic, minified identity/gzip HTML assets for ESP-IDF."""
import argparse
import gzip
import hashlib
import re
from pathlib import Path


COMMON_WEB = Path(__file__).resolve().parents[2] / 'web'


def asset_path(source: Path, name: str) -> Path:
    root = COMMON_WEB if name.startswith('@common/') else source.parent
    relative = name.removeprefix('@common/')
    path = (root / relative).resolve()
    if not path.is_relative_to(root.resolve()):
        raise ValueError(f'Asset escapes its source directory: {name}')
    return path


def source_files(source: Path) -> list[Path]:
    names = re.findall(r'(?:href|src)="([^"\n]+\.(?:css|js))"', source.read_text(encoding='utf-8'))
    return [source, *(asset_path(source, name) for name in names)]


def render_source(source: Path) -> str:
    html = source.read_text(encoding='utf-8')
    html = re.sub(r'<link rel="stylesheet" href="([^"\n]+)"\s*>',
                  lambda m: '<style>' + asset_path(source, m[1]).read_text(encoding='utf-8') + '</style>', html)
    html = re.sub(r'<script src="([^"\n]+)"></script>',
                  lambda m: '<script>' + asset_path(source, m[1]).read_text(encoding='utf-8') + '</script>', html)
    return re.sub(r'</script>\s*<script>', '\n', html)


def build(source: Path) -> tuple[bytes, bytes]:
    try:
        import minify_html
    except ImportError as error:
        raise RuntimeError(
            'Install web build dependencies: python -m pip install -r '
            'components/device_common/tools/web/requirements.txt'
        ) from error
    plain = minify_html.minify(
        render_source(source), minify_js=True, minify_css=True,
        keep_closing_tags=True, keep_html_and_head_opening_tags=True,
    ).encode('utf-8')
    return plain, gzip.compress(plain, compresslevel=9, mtime=0)


def generate(source: Path, output: Path):
    plain, compressed = build(source)
    lines = ['// Generated by tools/web/build_web.py; do not edit.', '#pragma once']
    for name, data in [('Identity', plain), ('Gzip', compressed)]:
        lines.append(f'inline constexpr unsigned char kWeb{name}[] = {{')
        lines.extend('  ' + ','.join(str(b) for b in data[i:i+24]) + ','
                     for i in range(0, len(data), 24))
        lines.append('};')
        digest = hashlib.sha256(data).hexdigest()[:24]
        lines.append(f'inline constexpr char kWeb{name}Etag[] = "\\"{digest}\\"";')
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    # Useful for browser tests and inspecting exactly what the device serves.
    output.with_suffix('.html').write_bytes(plain)
    output.with_suffix('.html.gz').write_bytes(compressed)
    print(f'Web: {source.stat().st_size} B source -> {len(plain)} B minified '
          f'-> {len(compressed)} B gzip')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    generate(args.source, args.output)
